### ISSUE TITLE
Minor reader design refresh

### ISSUE THREAD

**Issue by zdavis** [ManifoldScholar/manifold#2046]
This issue is a placeholder for various design improvements that need to be made to the reader.

- [x] Add a "reset" button to the typography/bg color controls drawer (#887)
- [x] Revisit the header icons to make sure they match updated icon look and feel.
- [x] Show interface for generating permalink to a selection (#2104)
- [x] Design mobile annotation popup (#1938)
- [ ] Add a simple mechanism to get the URL of an annotation

**Comment by zdavis** [comment]
Done as part of v4
